In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/jaswanthparna/Datasets/refs/heads/main/breast-cancer.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [3]:
df.shape

(569, 32)

In [5]:
df.drop(columns=['id'], inplace= True)

In [6]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

train test split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

scaling

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train

array([[-0.52415658, -0.30211921, -0.53088582, ..., -0.87258856,
        -0.78570266, -0.37946812],
       [-1.46474016, -0.90329892, -1.42403317, ..., -1.01366793,
        -0.74120711, -0.54122338],
       [ 1.49629261, -0.17430935,  1.42574928, ...,  1.4412348 ,
         1.01159964, -0.0727845 ],
       ...,
       [-0.1086032 ,  1.34284104, -0.12637918, ...,  0.06236635,
        -0.39636662, -0.55967867],
       [-0.28915398,  0.0103049 , -0.27268127, ..., -0.23894758,
         1.10535812,  0.40053961],
       [-0.65312142, -0.91276632, -0.66599767, ..., -0.5420858 ,
        -0.21520617, -0.3376723 ]])

In [12]:
X_test

array([[ 1.78001526,  1.78070815,  1.76560117, ...,  1.53397016,
         0.58889194, -0.43212   ],
       [ 2.05514026,  0.88367228,  1.91065991, ...,  1.31657414,
        -0.12462595, -0.4896571 ],
       [ 0.06621581,  0.90260707,  0.13555545, ...,  0.95627445,
         3.60028704,  3.27413801],
       ...,
       [ 0.65085642,  0.60911776,  0.67973293, ..., -0.14590816,
        -0.26129085, -0.25788028],
       [ 0.28688898,  1.39491172,  0.18404651, ..., -1.29689086,
        -2.12215822, -1.58720451],
       [-0.02549252, -0.63584495, -0.08824945, ..., -0.79171116,
        -0.35187107, -0.39629501]])

In [13]:
y_train

480    B
358    B
56     M
437    B
546    B
      ..
394    B
157    B
100    M
331    B
344    B
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [14]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [15]:
y_train

array([0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,

Numpy arrays to PyTorch tensors

In [16]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [17]:
X_train_tensor.shape

torch.Size([455, 30])

In [18]:
y_train_tensor.shape

torch.Size([455])

Defining the model

In [19]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


Important Parameters

In [20]:
learning_rate = 0.1
epochs = 25

Training Pipeline

In [21]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.2641453786766466
Epoch: 2, Loss: 3.1416983166578674
Epoch: 3, Loss: 3.021095462052027
Epoch: 4, Loss: 2.90076324699291
Epoch: 5, Loss: 2.7746032813984325
Epoch: 6, Loss: 2.641929840183265
Epoch: 7, Loss: 2.505660222773899
Epoch: 8, Loss: 2.3718622586790405
Epoch: 9, Loss: 2.2399467442306347
Epoch: 10, Loss: 2.111566037663073
Epoch: 11, Loss: 1.984567534057397
Epoch: 12, Loss: 1.858326911011437
Epoch: 13, Loss: 1.7353415475469363
Epoch: 14, Loss: 1.6147021625390665
Epoch: 15, Loss: 1.497199036370845
Epoch: 16, Loss: 1.3830354137764096
Epoch: 17, Loss: 1.281074314574186
Epoch: 18, Loss: 1.1917877823406577
Epoch: 19, Loss: 1.1150486087676958
Epoch: 20, Loss: 1.0501049777251408
Epoch: 21, Loss: 0.9957359390913814
Epoch: 22, Loss: 0.9504851745838214
Epoch: 23, Loss: 0.9128640611777142
Epoch: 24, Loss: 0.8814868163372271
Epoch: 25, Loss: 0.8551467836224019


In [22]:
model.weights

tensor([[-0.2274],
        [-0.0895],
        [ 0.5505],
        [-0.1670],
        [ 0.0402],
        [-0.1693],
        [-0.5592],
        [-0.3049],
        [ 0.4339],
        [ 0.0475],
        [-0.0639],
        [ 0.2717],
        [ 0.3789],
        [ 0.4316],
        [ 0.1559],
        [ 0.0517],
        [ 0.2192],
        [ 0.2930],
        [ 0.4538],
        [-0.0730],
        [-0.0076],
        [ 0.2776],
        [-0.3036],
        [-0.2048],
        [-0.0086],
        [-0.0148],
        [ 0.1439],
        [ 0.3526],
        [-0.1844],
        [-0.0132]], dtype=torch.float64, requires_grad=True)

In [23]:
model.bias

tensor([-0.1624], dtype=torch.float64, requires_grad=True)

Evaluation

In [24]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5761772990226746
